export QT_QPA_PLATFORMTHEME="qt5ct"
export EDITOR='nvim'
export VISUAL='nvim'
export BROWSER='librewolf'
export LESS='-gi'
export N64_LIBGCCDIR="/opt/crashsdk/lib/gcc/mips64-elf/11.2.0"
PATH=$PATH:/opt/crashsdk/bin; export PATH
#export AUDIO='deadbeef'
export QT_STYLE_OVERRIDE=kvantum
#export VDPAU_DRIVER='radeonsi'
#export allow_rgb10_configs=false
export VKBASALT_CONFIG_FILE=/home/qube/.config/vkBasalt/vkBasalt.conf
